# Generated by Django 5.1.2 on 2025-04-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('headline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('feedback', models.TextField()),
                ('github_link', models.URLField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SelfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_intro', models.TextField()),
                ('bio', models.TextField()),
                ('achievements_image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('achievements_desc', models.TextField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.personalinfo')),
            ],
        ),
    ]
